baseURL = "https://master.d2fvrafk9v089j.amplifyapp.com/"
languageCode = "en-us"
title = "AWS HPC Workshops"
theme = "hugo-learn-hpc"
uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
googleAnalytics = "UA-100198268-2"


[blackfriday]
hrefTargetBlank = true

[params]
themeVariant = "mine"
showVisitedLinks = true
description = "AWS HPC Workshops"
disableSearch = false
disableAssetsBusting = false
disableLanguageSwitchingButton = true
disableShortcutsTitle = false


[outputs]
home = [ "HTML", "AMP", "RSS", "JSON"]
page = [ "HTML", "AMP"]


[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false


[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> AWS - HPC"
url = "https://aws.amazon.com/hpc/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-users'></i> Authors"
url = "/authors.html"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Feedback"
url = "https://survey.immersionday.com/Rs8ggvVGR"
weight = 30

[[menu.shortcuts]]
name = "<i class='fas fa-bookmark'></i> Contact Us"
url="https://pages.awscloud.com/PEARC20Contact.html"
weight = 40

